
# gateway-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gateway-rolebinding
subjects:
- kind: ServiceAccount
  name: gateway-sa
roleRef:
  kind: Role
  name: gateway-role
  apiGroup: rbac.authorization.k8s.io