server:
  port: 8080
<<<<<<< HEAD

=======
 
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
spring:
  application:
    name: publication
---
<<<<<<< HEAD

=======
 
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: publication
#<<< EDA / Topic Name
          destination: ktlib
#>>> EDA / Topic Name
          contentType: application/json
        event-out:
#<<< EDA / Topic Name
          destination: ktlib
#>>> EDA / Topic Name
          contentType: application/json
<<<<<<< HEAD

=======
        requestedPublish-out-0:
          destination: ktlib
          content-type: application/json
 
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
<<<<<<< HEAD


server:
  port: 8084

---

=======
 
 
server:
  port: 8084
 
---
 
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: publication
          destination: ktlib
          contentType: application/json
        event-out:
          destination: ktlib
<<<<<<< HEAD
          contentType: application/json


=======
          contentType: application/json
>>>>>>> cc51f632aa39de85878eeed3e45ae4baeaf95442
