server:
  port: 8080

spring:
  application:
    name: user

jwt:
  secret: your_service_jwt_secret_key
  expiration: 86400000 # 1 day in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
          destination: ktlib
          contentType: application/json
        event-out:
          destination: ktlib
          contentType: application/json

server:
  port: 8087

---

spring:
  profiles: docker
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: user
          destination: ktlib
          contentType: application/json
        event-out:
          destination: ktlib
          contentType: application/json

jwt:
  secret: your_service_jwt_secret_key
  expiration: 86400000 # 1 day in milliseconds

management:
  endpoints:
    web:
      exposure:
        include: health,info
