apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  # istio router 코
  # ports:
  #   - name: http
  #     protocol: TCP
  #     port: 8080
  #     targetPort: 80
