server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://localhost:8087
          predicates:
            - Path=/login/**
        - id: user
          uri: http://localhost:8087
          predicates:
            - Path=/users/**

        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/authors/**, /authorLists/**
        - id: manuscript
          uri: http://localhost:8083
          predicates:
            - Path=/manuscripts/**, /manuscriptLists/**
        - id: publication
          uri: http://localhost:8084
          predicates:
            - Path=/publishes/**
        - id: book
          uri: http://localhost:8085
          predicates:
            - Path=/books/**, /bookLists/**
        - id: point
          uri: http://localhost:8086
          predicates:
            - Path=/points/**, /pointsLists/**
        - id: subscribe
          uri: http://localhost:8090    # 실제 subscribe 서비스 포트로 수정
          predicates:
            - Path=/subscribeSus/**, /subscribeLists/**
        - id: periodsubscribe
          uri: http://localhost:8089
          predicates:
            - Path=/periodSubscribes/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ["*"]
            allowedMethods: ["*"]
            allowedHeaders: ["*"]
            allowCredentials: true

---

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          # Secret 기반 JWT 인증을 적용하려면 JwtAuthConfig로 전환 필요