server:
  port: 8080

spring:
  application:
    name: gateway

  
    
    # spring:
    #   profiles: docker
    #   cloud:
    #     gateway:
    #       routes:
    #         # User 서비스
    #         - id: user
    #           uri: http://user:8080
    #           predicates:
    #             - Path=/auth/**, /users/**
    
    #         # 다른 마이크로서비스 경로들
    #         - id: author
    #           uri: http://author:8080
    #           predicates:
    #             - Path=/authors/**
    #         - id: manuscript
    #           uri: http://manuscript:8080
    #           predicates:
    #             - Path=/manuscripts/**
    #         - id: publication
    #           uri: http://publication:8080
    #           predicates:
    #             - Path=/publishes/**
    #         - id: book
    #           uri: http://book:8080
    #           predicates:
    #             - Path=/books/**
    #         - id: point
    #           uri: http://point:8080
    #           predicates:
    #             - Path=/points/**
    #         - id: subscribe
    #           uri: http://subscribe:8080
    #           predicates:
    #             - Path=/subscribeSus/**
    #         - id: periodsubscribe
    #           uri: http://periodsubscribe:8080
    #           predicates:
    #             - Path=/periodSubscribes/**
    
    #         # Frontend 서비스 (가장 마지막)
    #         - id: frontend
    #           uri: http://frontend:8080
    #           predicates:
    #             - Path=/**
    