server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://localhost:8082
          predicates:
            - Path=/api/authors/**, /api/authorLists/**
          filters:
            - StripPrefix=1

        - id: manuscript
          uri: http://localhost:8083
          predicates:
            - Path=/api/manuscripts/**, /api/manuscriptLists/**
          filters:
            - StripPrefix=1

        - id: publication
          uri: http://localhost:8084
          predicates:
            - Path=/api/publishes/**
          filters:
            - StripPrefix=1

        - id: book
          uri: http://localhost:8085
          predicates:
            - Path=/api/books/**, /api/bookLists/**
          filters:
            - StripPrefix=1

        - id: point
          uri: http://localhost:8086
          predicates:
            - Path=/api/points/**, /api/pointsLists/**
          filters:
            - StripPrefix=1

        - id: user
          uri: http://localhost:8087
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: subscribe
          uri: http://localhost:8088
          predicates:
            - Path=/api/subscribeSus/**, /api/subscribeLists/**
          filters:
            - StripPrefix=1

        - id: periodsubscribe
          uri: http://localhost:8089
          predicates:
            - Path=/api/periodSubscribes/**
          filters:
            - StripPrefix=1

        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: author
          uri: http://author:8080
          predicates:
            - Path=/api/authors/**
          filters:
            - StripPrefix=1

        - id: manuscript
          uri: http://manuscript:8080
          predicates:
            - Path=/api/manuscripts/**
          filters:
            - StripPrefix=1

        - id: publication
          uri: http://publication:8080
          predicates:
            - Path=/api/publishes/**
          filters:
            - StripPrefix=1

        - id: book
          uri: http://book:8080
          predicates:
            - Path=/api/books/**
          filters:
            - StripPrefix=1

        - id: point
          uri: http://point:8080
          predicates:
            - Path=/api/points/**
          filters:
            - StripPrefix=1

        - id: user
          uri: http://user:8080
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: subscribe
          uri: http://subscribe:8080
          predicates:
            - Path=/api/subscribeSus/**
          filters:
            - StripPrefix=1

        - id: periodsubscribe
          uri: http://periodsubscribe:8080
          predicates:
            - Path=/api/periodSubscribes/**
          filters:
            - StripPrefix=1

        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
